services:
  project-manager:
    image: ghcr.io/Njordics/forsetiflow:latest
    container_name: project-manager
    user: "${UID}:${GID}"
    ports:
      - "51001:51001"
    volumes:
      - ./data:/app/instance
    restart: unless-stopped
